export const correctionFormURL="https://docs.google.com/forms/d/e/1FAIpQLSc1ik61v7easSzsP3jZt4GLsZGTLg-LXoKegsiDcizOka7LtA/viewform?usp=publish-editor";
export const words={
ja:{
 eyebrow:'暮らしを支える制度の入口',hero:'使えそうな支援を、見つける。',intro:'答えられる条件だけで、東京都・目黒区の制度を探せます。',scope:'東京都・目黒区／個人運営の非公式ガイド',count:'の支援制度',heroNote:'受給を決める診断ではありません。気になる制度は、公式窓口で条件を確認しましょう。',
 filters:'あなたの条件',reset:'リセット',optional:'すべて任意。入力は保存されません。',filterFoot:'わからない項目は空欄のままで大丈夫です。',foreignTitle:'外国人向け条件も確認する',resultsKicker:'支援の候補を見つける',results:'制度一覧',resultCount:n=>n+'制度',resultNote:'不明な条件があっても制度は表示します。最終判断は公式窓口でご確認ください。',details:'条件と申請方法を見る',close:'閉じる',checked:'最終確認',next:'次回確認期限',operator:'実施主体',official:'公式ページ',additional:'追加の公式根拠',unverifiedLink:'取得未確認の参考先',noGuarantee:'これは制度を探すための案内です。受給の可否は公式窓口で確認してください。',foreign:'外国人向けの確認',unknown:'未確認事項',conditions:'主な条件',benefit:'支援内容',apply:'申請方法',documents:'主要書類',caution:'注意事項',dates:'期限・期間',extra:'この制度だけ、もう少し確認する（任意）',extraNote:'入力はこの制度の確認だけに使います。本人と子どもの住民登録を取り違えないでください。',translation:'英語は当サイトによる説明訳です。',footer:'制度の情報は変わることがあります。申請書類や個人情報をこのサイトへ送らないでください。',skip:'制度一覧へ',loadError:'制度を読み込めませんでした。ローカルHTTPサーバーから開き、再読み込みしてください。',noDate:'未確認',ongoingDates:'一律の申請期限は確認できませんでした。個別の期限は公式窓口で確認してください。',endTime:'締切時刻は未確認です。締切日は公式ページでご確認ください。',budget:'予算に達すると期限前に終了する場合があります。',candidate:'入力した条件では候補です',review:'追加条件を確認してください',mismatch:'入力した条件では対象外の可能性',ageInvalid:'年齢は0以上の整数で入力してください。不正な入力は不明として扱います。',
 states:{open:'受付中（確認時点）',ongoing:'常設（確認時点）',planned:'予定',closed:'受付終了',unknown:'状態未確認',stale:'情報の再確認が必要です',deadline_check:'締切日・時刻を要確認',purchase_ended:'対象購入期間終了'},
 reasons:{card:'現在の参加経路にはマイナンバーカードが必要です。',age:'現在の年齢は、この条件と一致しません。',registration:'申告された住民登録地域が条件と一致しません。',shop:'今回の購入店は登録販売店ではありません。',installation:'今回の設置地域は対象地域と異なります。',child_age:'現在の対象児年齢の条件と一致しません。過年度分は公式窓口へ。',purchase:'助成決定前の購入は対象外です。',tax:'本人の住民税非課税という条件と一致しません。',mortgage:'住宅ローンだけの支援は、この家賃補助の範囲外です。',insurance:'現在の保険加入条件を確認してください。',outpatient:'入院費だけの支援は、この精神通院制度の範囲外です。',nhi:'この軽減は目黒区の国民健康保険向けです。',school:'この学校区分は、当該制度の対象外です。他の支援は窓口へ。',incomplete:'所得・書類・個別条件など、公式窓口での確認が必要です。'},
 fields:{region:'居住地',adult_age:'本人年齢',child_band:'子どもの年代',interests:'興味分野',resident_tax:'本人の住民税',housing:'住居',nationality_group:'国籍区分',residence_status_group:'在留区分',registered_region:'対象者の住民登録',card_available:'マイナンバーカード',insurance:'対象者の健康保険',school_type:'学校の区分',support_scope:'探している支援',purchase_stage:'購入と助成決定',purchase_store:'購入予定・購入店舗',equipment_region:'設備の設置場所'},
 options:{unknown:'わからない・未回答',meguro:'目黒区',other_tokyo:'東京都内（目黒区以外）',outside_tokyo:'東京都以外',under18:'0〜17歳',18:'18歳',over18:'19歳以上',none:'子どもなし',all:'すべて',living:'生活・ポイント',children:'子育て・教育',medical:'医療・障害',older:'高齢者',housing:'住宅',energy:'省エネ・設備',income:'低所得・保険',taxed:'課税',exempt:'非課税',owner:'持家',rental:'賃貸',other:'その他',japanese:'日本国籍',foreign:'外国籍',decline:'回答しない',permanent:'永住',special_permanent:'特別永住',long_term:'定住',work:'就労系',spouse:'配偶者等',yes:'あり',no:'なし',meguro_nhi:'目黒区の国民健康保険',other_japan_public:'その他の国内公的健康保険',not_enrolled:'現在未加入',public_compulsory:'国公立の小・中学校等',private:'私立',international:'インターナショナル',special_needs:'特別支援学校',rent:'家賃',owner_mortgage:'住宅ローンだけ',mental_outpatient:'継続する精神通院',inpatient_only:'入院費だけ',before_approval:'助成決定前・未購入',purchased_before_approval:'助成決定より前に購入済み',registered:'登録販売店',unregistered:'未登録店舗'},
 events:{application_window:'申請期間',eligible_purchase:'対象購入期間',installation_handover:'設置・引渡期間',payment_batch_cutoff:'支払回の申請締切',retroactive_claim:'遡及の取扱い',certificate_renewal:'証の更新',points_expiry:'ポイント利用期限'}
},
en:{
 eyebrow:'A starting point for everyday support',hero:'Find support for your everyday life.',intro:'Explore programs in Tokyo and Meguro. Answer only what you feel comfortable sharing.',scope:'Tokyo and Meguro / An independent, unofficial guide',count:'support programs',heroNote:'This is a guide, not an eligibility decision. Check the full requirements with the official program office.',
 filters:'Your circumstances',reset:'Reset',optional:'All answers are optional and are not saved.',filterFoot:'Leave anything you are unsure about unanswered.',foreignTitle:'Information for foreign residents',resultsKicker:'Explore your options',results:'Support programs',resultCount:n=>n+' programs',resultNote:'Programs stay visible when details are unknown. The official office makes the final decision.',details:'View conditions and how to apply',close:'Close',checked:'Last checked',next:'Next review due',operator:'Provided by',official:'Official page',additional:'Additional official reference',unverifiedLink:'Reference not retrieved',noGuarantee:'This tool helps you find programs. The program office decides eligibility.',foreign:'For foreign residents',unknown:'What remains unconfirmed',conditions:'Main conditions',benefit:'Support available',apply:'How to apply',documents:'Main documents',caution:'Please check',dates:'Dates and deadlines',extra:'Check a few details for this program (optional)',extraNote:'These answers apply only to this program. Use the details of the person or child concerned.',translation:'The English text is our own plain-language explanation.',footer:'Program information may change. Do not send application documents or personal information to this site.',skip:'Skip to programs',loadError:'Program data could not be loaded. Open this site through a local HTTP server and reload.',noDate:'Not confirmed',ongoingDates:'We have not confirmed one general application deadline. Ask the official office about any deadlines for your case.',endTime:'The closing time is not confirmed. Check the official page on the deadline date.',budget:'Applications may close early if the budget is used up.',candidate:'Matches the details you entered',review:'More conditions to check',mismatch:'May not meet a stated condition',ageInvalid:'Enter a whole number of zero or more. Invalid input is treated as unknown.',
 states:{open:'Applications open (when checked)',ongoing:'Ongoing (when checked)',planned:'Not yet open',closed:'Applications closed',unknown:'Status not confirmed',stale:'This information needs to be checked again.',deadline_check:'Check the deadline time',purchase_ended:'Eligible purchase period ended'},
 reasons:{card:'A My Number Card is required for the current application route.',age:'The current age does not match the stated condition.',registration:'The stated residence-registration area does not match.',shop:'This purchase is not through a registered shop.',installation:'This installation is outside the stated area.',child_age:'The child is outside the current age range. Ask the office about earlier periods.',purchase:'Purchases made before approval are not covered.',tax:'This requires personal resident-tax exemption.',mortgage:'Mortgage-only support is outside this rent program.',insurance:'Check the current insurance-membership requirement.',outpatient:'Inpatient-only support is outside this outpatient program.',nhi:'This reduction is for Meguro National Health Insurance.',school:'This school type is outside this program. Ask about other support.',incomplete:'Income, documents and individual circumstances still need an official check.'},
 fields:{region:'Where you live',adult_age:'Your age',child_band:"Child's age group",interests:'Area of interest',resident_tax:'Your resident tax',housing:'Your home',nationality_group:'Nationality',residence_status_group:'Residence status',registered_region:"Person's registered residence",card_available:'My Number Card',insurance:"Person's health insurance",school_type:'School type',support_scope:'Support you are seeking',purchase_stage:'Purchase and approval',purchase_store:'Shop for this purchase',equipment_region:'Installation area'},
 options:{unknown:'Not sure / unanswered',meguro:'Meguro',other_tokyo:'Elsewhere in Tokyo',outside_tokyo:'Outside Tokyo',under18:'Age 0–17',18:'Age 18',over18:'Age 19 or over',none:'No children',all:'All areas',living:'Everyday living',children:'Children and education',medical:'Health and disability',older:'Older people',housing:'Housing',energy:'Energy and equipment',income:'Income and insurance',taxed:'Taxable',exempt:'Exempt',owner:'Owner-occupied',rental:'Rented',other:'Other',japanese:'Japanese national',foreign:'Foreign national',decline:'Prefer not to answer',permanent:'Permanent resident',special_permanent:'Special permanent resident',long_term:'Long-term resident',work:'Work-related',spouse:'Spouse-related',yes:'Yes',no:'No',meguro_nhi:'Meguro National Health Insurance',other_japan_public:'Other Japanese public insurance',not_enrolled:'Not currently enrolled',public_compulsory:'Public elementary / junior high',private:'Private school',international:'International school',special_needs:'Special-needs school',rent:'Rent',owner_mortgage:'Mortgage payments only',mental_outpatient:'Ongoing mental health outpatient care',inpatient_only:'Inpatient costs only',before_approval:'Not purchased; before approval',purchased_before_approval:'Purchased before approval',registered:'Registered shop',unregistered:'Unregistered shop'},
 events:{application_window:'Application period',eligible_purchase:'Eligible purchase dates',installation_handover:'Installation and handover',payment_batch_cutoff:'Payment-round application cutoff',retroactive_claim:'Backdated support',certificate_renewal:'Certificate renewal',points_expiry:'Points expiry'}
}};
export const policies={
about:{ja:{title:'このサイトについて',text:['生活支援ナビは、東京都・目黒区の支援制度を見つけやすくする個人運営の非公式ガイドです。公的機関ではありません。','第一版は10制度を掲載しています。すべての制度を網羅していません。入力した条件だけで受給資格を決めず、公式ページや窓口へつなぎます。','一次情報を参照し、確認日・不明事項・期限を示します。常時更新は保証しません。英語は当サイトの説明訳です。']},en:{title:'About this guide',text:['Tokyo Support Finder is an independent, unofficial guide to support in Tokyo and Meguro. It is not a public agency.','This first version lists 10 programs. It is not a complete list. Your answers help identify programs to check; they do not establish eligibility.','We use official sources and show review dates, deadlines and uncertainties. Updates are not real-time. English explanations are our own.']}},
privacy:{ja:{title:'Privacy Policy',text:['条件はブラウザのメモリ内で処理します。ログイン機能はなく、入力条件を保存・送信しません。再読み込みで消えます。CookieやlocalStorageにも保存しません。','広告・アクセス解析・AI APIは使用していません。氏名、詳細住所、所得の証明、番号、書類の入力・アップロードは求めません。','サイトのHTML・制度データなどの読み込みには通常の通信が発生します。公開後の配信事業者には通常のアクセス情報が届き得ますが、入力条件は送信しません。','公式サイトやGoogle Formsへの移動後は、移動先の規則が適用されます。リンクに入力条件は付加しません。訂正内容はGoogle Formsで送信した場合にGoogleと運営者へ届き、掲載情報の確認・訂正に利用します。メールアドレスの自動収集は行いません。個人情報や申請書類を書き込まないでください。']},en:{title:'Privacy Policy',text:['Your answers are processed only in browser memory. There is no login. Answers are not saved or sent and are cleared on reload. We do not store them in cookies or localStorage.','We use no advertising, analytics or AI API. We do not ask for names, detailed addresses, income evidence, identity numbers or uploaded documents.','Loading the site and program data involves normal network requests. Once hosted, the hosting provider may receive standard access information, but not your answers.','Official sites and Google Forms have their own policies. We do not add your answers to links. If you submit a correction through Google Forms, Google and the guide operator receive it to review and correct the guide. The form does not automatically collect email addresses. Do not include personal information or application documents.']}},
disclaimer:{ja:{title:'免責事項',text:['このサイトは非公式の探索ガイドです。受給資格・支給額・申請の成功を保証しません。最終判断は公式窓口が行います。','制度・期限・予算は変更されることがあります。必ず公式ページの最新情報をご確認ください。未確認の条件は「制限なし」を意味しません。','申請代行や個別の受給相談は行いません。申請書類や個人情報をこのサイトへ送らないでください。']},en:{title:'Disclaimer',text:['This is an unofficial discovery guide. We do not guarantee eligibility, an award amount or a successful application. The official program office makes the final decision.','Rules, deadlines and funding may change. Check current official information. An unconfirmed condition does not mean there is no restriction.','We do not handle applications or individual eligibility consultations. Do not send application documents or personal information to this site.']}},
corrections:{ja:{title:'掲載情報の誤り・訂正連絡',text:['掲載情報の誤り・公式情報の更新・訂正連絡は、専用のGoogleフォームからお知らせください。','必須は誤り・訂正内容です。制度名またはページ、公式根拠URLは任意です。ログイン不要で利用でき、メールアドレスは自動収集しません。','個別の受給資格・申請方法・個人事情の相談や申請は受け付けません。氏名・住所・所得・在留証明・診断書などの個人情報や書類を送らないでください。制度の相談は各公式窓口へお願いします。']},en:{title:'Report an error in this guide',text:['Use our dedicated Google Form to report errors, updated official information or corrections to this guide.','Only the correction details are required. The program or page and an official source URL are optional. No sign-in is required, and email addresses are not automatically collected.','We do not provide advice on individual eligibility, application procedures or personal circumstances, and we do not handle applications. Do not send names, addresses, income details, residence documents, medical records or other personal information. Ask the official program office about your case.']}}
};
